import type { FC } from 'hono/jsx';
import { AdminLayout } from '../layouts/AdminLayout.js';
import { Button } from '../components/Button.js';
import { ClientScript } from '../components/ClientScript.js';

const script = String.raw`
(() => {
  const kitchenForm = document.getElementById('kitchen-form'); const schoolForm = document.getElementById('school-form'); const kitchenRows = document.getElementById('kitchen-rows'); const schoolRows = document.getElementById('school-rows'); const message = document.getElementById('location-message');
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char])); const api = async (url, options) => { const response = await fetch(url, options); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || 'Permintaan gagal.'); return data; }; const notify = (text, error = false) => { message.textContent = text; message.className = error ? 'mb-4 rounded-lg bg-error-container text-on-error-container px-4 py-3' : 'mb-4 rounded-lg bg-tertiary-fixed text-on-tertiary-fixed px-4 py-3'; message.hidden = !text; };
  const fields = ['name','code','address','village','district','city','province','postal_code','capacity']; const schoolFields = ['name','npsn','address','village','district','city','province','postal_code','student_count']; const set = (form, name, value) => form.elements[name].value = value ?? '';
  const load = async () => { try { const [kitchens, schools] = await Promise.all([api('/api/admin/kitchens?per_page=100'), api('/api/admin/schools?per_page=100')]); document.getElementById('school-kitchen').innerHTML = '<option value="">Pilih dapur</option>'+kitchens.data.map((item) => '<option value="'+item.id+'">'+esc(item.name)+'</option>').join(''); kitchenRows.innerHTML = kitchens.data.length ? kitchens.data.map((item) => '<tr class="border-b border-surface-variant"><td class="p-3"><strong>'+esc(item.name)+'</strong><div class="text-xs">'+esc(item.code)+'</div></td><td class="p-3">'+esc(item.city)+'</td><td class="p-3">'+esc(item.capacity)+'</td><td class="p-3 text-right"><button type="button" data-edit-kitchen="'+item.id+'" class="text-primary mr-3">Edit</button><button type="button" data-delete-kitchen="'+item.id+'" class="text-error">Hapus</button></td></tr>').join('') : '<tr><td colspan="4" class="p-6 text-center">Belum ada dapur.</td></tr>'; schoolRows.innerHTML = schools.data.length ? schools.data.map((item) => '<tr class="border-b border-surface-variant"><td class="p-3">'+esc(item.name)+'</td><td class="p-3">'+esc(item.npsn)+'</td><td class="p-3">'+esc(item.kitchen?.name)+'</td><td class="p-3">'+esc(item.student_count)+'</td><td class="p-3 text-right"><button type="button" data-edit-school="'+item.id+'" class="text-primary mr-3">Edit</button><button type="button" data-delete-school="'+item.id+'" class="text-error">Hapus</button></td></tr>').join('') : '<tr><td colspan="5" class="p-6 text-center">Belum ada sekolah.</td></tr>'; notify(''); } catch (error) { notify(error.message, true); } };
  kitchenForm.addEventListener('submit', async (event) => { event.preventDefault(); const payload = Object.fromEntries(new FormData(kitchenForm).entries()); payload.capacity = Number(payload.capacity); const id = kitchenForm.dataset.id; try { await api(id ? '/api/admin/kitchens/'+id : '/api/admin/kitchens', {method:id?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}); kitchenForm.reset(); kitchenForm.dataset.id = ''; document.getElementById('kitchen-submit').textContent = 'Simpan Dapur'; notify(id ? 'Dapur berhasil diperbarui.' : 'Dapur berhasil dibuat.'); load(); } catch (error) { notify(error.message, true); } });
  schoolForm.addEventListener('submit', async (event) => { event.preventDefault(); const payload = Object.fromEntries(new FormData(schoolForm).entries()); payload.kitchen_id = Number(payload.kitchen_id); payload.student_count = Number(payload.student_count); const id = schoolForm.dataset.id; try { await api(id ? '/api/admin/schools/'+id : '/api/admin/schools', {method:id?'PATCH':'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)}); schoolForm.reset(); schoolForm.dataset.id = ''; document.getElementById('school-submit').textContent = 'Simpan Sekolah'; notify(id ? 'Sekolah berhasil diperbarui.' : 'Sekolah berhasil dibuat.'); load(); } catch (error) { notify(error.message, true); } });
  document.addEventListener('click', async (event) => { const button = event.target.closest('button[data-edit-kitchen],button[data-edit-school],button[data-delete-kitchen],button[data-delete-school]'); if (!button) return; try { if (button.dataset.editKitchen) { const item = (await api('/api/admin/kitchens/'+button.dataset.editKitchen)).data; fields.forEach((name) => set(kitchenForm, name, item[name])); kitchenForm.dataset.id = item.id; document.getElementById('kitchen-submit').textContent = 'Perbarui Dapur'; return; } if (button.dataset.editSchool) { const item = (await api('/api/admin/schools/'+button.dataset.editSchool)).data; schoolFields.forEach((name) => set(schoolForm, name, item[name])); set(schoolForm, 'kitchen_id', item.kitchen_id); schoolForm.dataset.id = item.id; document.getElementById('school-submit').textContent = 'Perbarui Sekolah'; return; } if (!confirm('Hapus data ini?')) return; const kind = button.dataset.deleteKitchen ? 'kitchens' : 'schools'; const id = button.dataset.deleteKitchen || button.dataset.deleteSchool; await api('/api/admin/'+kind+'/'+id, {method:'DELETE'}); notify('Data berhasil dihapus.'); load(); } catch (error) { notify(error.message, true); } }); load();
})();
`;

const textInput = (name: string, label: string, extra = '') => <label>{label}<input name={name} required class="mt-1 w-full border border-outline-variant rounded-lg p-2" {...(extra ? { type: extra } : {})} /></label>;

export const AdminLokasiPage: FC = () => (
  <AdminLayout title="Dapur & Sekolah" activePage="/admin/lokasi">
    <div><div class="mb-8"><h2 class="font-display-lg text-display-lg text-on-surface">Dapur & Sekolah</h2><p class="font-body-md text-body-md text-on-surface-variant mt-1">Kelola master data dapur MBG dan sekolah yang dilayani.</p></div><div id="location-message" hidden></div><div class="grid grid-cols-1 xl:grid-cols-2 gap-6"><section class="bg-surface-container-lowest rounded-xl p-card-padding shadow-sm"><h3 class="font-headline-md text-headline-md mb-4">Tambah Dapur</h3><form id="kitchen-form" class="grid grid-cols-1 md:grid-cols-2 gap-3">{textInput('name','Nama')}{textInput('code','Kode')}{textInput('address','Alamat')}{textInput('village','Desa')}{textInput('district','Kecamatan')}{textInput('city','Kota')}{textInput('province','Provinsi')}{textInput('postal_code','Kode pos')}{textInput('capacity','Kapasitas','number')}<div class="md:col-span-2"><button id="kitchen-submit" class="bg-primary text-on-primary rounded-lg px-5 py-2">Simpan Dapur</button></div></form></section><section class="bg-surface-container-lowest rounded-xl p-card-padding shadow-sm"><h3 class="font-headline-md text-headline-md mb-4">Tambah Sekolah</h3><form id="school-form" class="grid grid-cols-1 md:grid-cols-2 gap-3">{textInput('name','Nama')}{textInput('npsn','NPSN')}{textInput('address','Alamat')}{textInput('village','Desa')}{textInput('district','Kecamatan')}{textInput('city','Kota')}{textInput('province','Provinsi')}{textInput('postal_code','Kode pos')}{textInput('student_count','Jumlah siswa','number')}<label>Dapur<select id="school-kitchen" name="kitchen_id" required class="mt-1 w-full border border-outline-variant rounded-lg p-2"><option value="">Pilih dapur</option></select></label><div class="md:col-span-2"><button id="school-submit" class="bg-primary text-on-primary rounded-lg px-5 py-2">Simpan Sekolah</button></div></form></section></div><div class="grid grid-cols-1 xl:grid-cols-2 gap-6 mt-6"><section class="bg-surface-container-lowest rounded-xl shadow-sm overflow-hidden"><h3 class="font-headline-md text-headline-md p-card-padding pb-3">Daftar Dapur</h3><div class="overflow-x-auto"><table class="w-full text-left"><thead class="bg-surface-container-low"><tr><th class="p-3">Dapur</th><th class="p-3">Kota</th><th class="p-3">Kapasitas</th><th class="p-3"></th></tr></thead><tbody id="kitchen-rows"></tbody></table></div></section><section class="bg-surface-container-lowest rounded-xl shadow-sm overflow-hidden"><h3 class="font-headline-md text-headline-md p-card-padding pb-3">Daftar Sekolah</h3><div class="overflow-x-auto"><table class="w-full text-left"><thead class="bg-surface-container-low"><tr><th class="p-3">Sekolah</th><th class="p-3">NPSN</th><th class="p-3">Dapur</th><th class="p-3">Siswa</th><th class="p-3"></th></tr></thead><tbody id="school-rows"></tbody></table></div></section></div></div><ClientScript>{script}</ClientScript>
  </AdminLayout>
);
