import type { FC } from 'hono/jsx';
import { AdminLayout } from '../layouts/AdminLayout.js';
import { Button } from '../components/Button.js';
import { ClientScript } from '../components/ClientScript.js';

const script = String.raw`
(() => {
  const rows = document.getElementById('aspiration-rows'); const message = document.getElementById('aspiration-message'); const modal = document.getElementById('aspiration-modal'); const form = document.getElementById('aspiration-form'); let currentId = null;
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char])); const api = async (url, options) => { const response = await fetch(url, options); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(response.status === 401 ? 'Sesi berakhir. Silakan masuk kembali.' : Object.values(data.errors || {}).join(' ') || data.message || 'Permintaan gagal.'); return data; }; const notify = (text, error = false) => {
    let target = message;
    if (error && !modal.classList.contains('hidden')) {
      target = form.querySelector('[role="alert"]');
      if (!target) { target = document.createElement('div'); target.setAttribute('role', 'alert'); form.prepend(target); }
    }
    target.textContent = text;
    target.className = 'md:col-span-2 mb-4 rounded-lg px-4 py-3 ' + (error ? 'bg-error-container text-on-error-container' : 'bg-tertiary-fixed text-on-tertiary-fixed');
    target.hidden = !text;
  };
  const load = async () => { try { const result = await api('/api/admin/aspirations?per_page=100&sort=newest'); rows.innerHTML = result.data.length ? result.data.map((item) => '<tr class="border-b border-surface-variant hover:bg-surface-container-low"><td class="p-3"><div class="font-semibold">'+esc(item.sender_name)+'</div><div class="text-xs text-on-surface-variant">'+esc(item.sender_email || '-')+'</div></td><td class="p-3">'+esc(item.category)+'</td><td class="p-3 max-w-md">'+esc(item.description)+'</td><td class="p-3">'+esc(item.status)+'</td><td class="p-3 text-right"><button type="button" data-edit="'+item.id+'" class="text-primary">Detail / Tanggapi</button></td></tr>').join('') : '<tr><td colspan="5" class="p-8 text-center text-on-surface-variant">Belum ada aspirasi.</td></tr>'; } catch (error) { notify(error.message, true); } };
  rows.addEventListener('click', async (event) => { const button = event.target.closest('button[data-edit]'); if (!button) return; try { const item = (await api('/api/admin/aspirations/'+button.dataset.edit)).data; currentId = item.id; form.querySelector('[role="alert"]')?.remove(); form.elements.status.value = item.status; form.elements.admin_response.value = item.admin_response || ''; document.getElementById('aspiration-detail').innerHTML = '<strong>'+esc(item.sender_name)+'</strong><br>'+esc(item.sender_email || '-')+'<br><br>'+esc(item.description); modal.classList.remove('hidden'); } catch (error) { notify(error.message, true); } });
  document.getElementById('aspiration-close').addEventListener('click', () => modal.classList.add('hidden')); form.addEventListener('submit', async (event) => { event.preventDefault(); try { const payload = Object.fromEntries(new FormData(form).entries()); if (!payload.admin_response.trim()) delete payload.admin_response; await api('/api/admin/aspirations/'+currentId, { method: 'PATCH', headers: {'content-type':'application/json'}, body: JSON.stringify(payload) }); modal.classList.add('hidden'); notify('Aspirasi berhasil diperbarui.'); load(); } catch (error) { notify(error.message, true); } }); load();
})();
`;

export const AspirasiPage: FC = () => (
  <AdminLayout title="Manajemen Aspirasi" activePage="/admin/aspirasi">
    <div><div class="mb-8"><h2 class="font-display-lg text-display-lg font-bold text-on-surface">Manajemen Aspirasi</h2><p class="font-body-md text-body-md text-on-surface-variant mt-2">Pantau dan tindak lanjuti umpan balik masyarakat.</p></div><div id="aspiration-message" hidden></div><div class="bg-surface-container-lowest rounded-xl shadow-sm overflow-hidden"><div class="p-card-padding border-b border-surface-variant flex justify-between items-center"><h3 class="font-headline-md text-headline-md">Daftar Aspirasi</h3><Button variant="secondary" shape="rounded" type="button" onclick="location.reload()">Muat ulang</Button></div><div class="overflow-x-auto"><table class="w-full text-left"><thead class="bg-surface-container-low"><tr><th class="p-3">Pengirim</th><th class="p-3">Kategori</th><th class="p-3">Aspirasi</th><th class="p-3">Status</th><th class="p-3 text-right">Aksi</th></tr></thead><tbody id="aspiration-rows"></tbody></table></div></div><div id="aspiration-modal" class="hidden fixed inset-0 z-30 bg-black/30 p-4 overflow-y-auto"><div class="bg-surface-card max-w-2xl mx-auto mt-10 rounded-xl p-6"><div class="flex justify-between items-center mb-5"><h3 class="font-headline-md text-headline-md">Detail & Tanggapan</h3><button id="aspiration-close" type="button" class="text-2xl" aria-label="Tutup">×</button></div><div id="aspiration-detail" class="bg-surface-container-low rounded-lg p-4 mb-4"></div><form id="aspiration-form" class="space-y-4"><label>Status<select name="status" class="mt-1 w-full border border-outline-variant rounded-lg p-2"><option value="pending">Pending</option><option value="in_progress">Dalam proses</option><option value="completed">Selesai</option><option value="rejected">Ditolak</option></select></label><label>Tanggapan<textarea name="admin_response" class="mt-1 w-full border border-outline-variant rounded-lg p-2 min-h-[120px]"></textarea></label><div class="flex justify-end"><button type="submit" class="bg-primary text-on-primary rounded-lg px-5 py-2">Simpan</button></div></form></div></div></div><ClientScript>{script}</ClientScript>
  </AdminLayout>
);
