import type { FC } from 'hono/jsx';
import { AdminLayout } from '../layouts/AdminLayout.js';
import { Button } from '../components/Button.js';
import { ClientScript } from '../components/ClientScript.js';

const script = String.raw`
(() => {
  const form = document.getElementById('finance-form'); const modal = document.getElementById('finance-modal'); const rows = document.getElementById('finance-rows'); const message = document.getElementById('finance-message');
  const esc = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
  const money = (value) => new Intl.NumberFormat('id-ID').format(Number(value || 0));
  const api = async (url, options) => { const response = await fetch(url, options); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.message || 'Permintaan gagal.'); return data; };
  const notify = (text, error = false) => { message.textContent = text; message.className = error ? 'mb-4 rounded-lg bg-error-container text-on-error-container px-4 py-3' : 'mb-4 rounded-lg bg-tertiary-fixed text-on-tertiary-fixed px-4 py-3'; message.hidden = !text; };
  const setValue = (name, value) => { form.elements[name].value = value ?? ''; };
  const loadOptions = async () => { const result = await api('/api/admin/kitchens?per_page=100'); document.getElementById('finance-kitchen').insertAdjacentHTML('beforeend', result.data.map((item) => '<option value="'+item.id+'">'+esc(item.name)+'</option>').join('')); };
  const render = (items) => { rows.innerHTML = items.length ? items.map((item) => '<tr class="border-b border-surface-variant hover:bg-surface-container-low"><td class="p-3">'+esc(item.transaction_date)+'</td><td class="p-3"><div class="font-semibold">'+esc(item.title)+'</div><div class="text-xs text-on-surface-variant">'+esc(item.kitchen?.name)+'</div></td><td class="p-3">'+esc(item.type)+' · '+esc(item.category)+'</td><td class="p-3 text-right '+(item.type === 'OUT' ? 'text-error' : 'text-tertiary')+'">Rp '+money(item.amount)+'</td><td class="p-3 text-right"><button type="button" data-edit="'+item.id+'" class="text-primary mr-3">Edit</button><button type="button" data-delete="'+item.id+'" class="text-error">Hapus</button></td></tr>').join('') : '<tr><td colspan="5" class="p-8 text-center text-on-surface-variant">Belum ada transaksi.</td></tr>'; };
  const load = async () => { try { const result = await api('/api/admin/finance/transactions?per_page=100&sort=newest'); render(result.data); const stats = await api('/api/admin/finance/statistics?year='+new Date().getFullYear()); const summary = stats.data.summary; document.getElementById('finance-balance').textContent = 'Rp '+money(summary.balance); document.getElementById('finance-income').textContent = 'Rp '+money(summary.total_income); document.getElementById('finance-expense').textContent = 'Rp '+money(summary.total_expenses); notify(''); } catch (error) { notify(error.message, true); } };
  const open = async (id) => { form.reset(); form.dataset.id = id || ''; document.getElementById('finance-modal-title').textContent = id ? 'Edit Transaksi' : 'Tambah Transaksi'; if (id) { const item = (await api('/api/admin/finance/transactions/'+id)).data; ['type','category','title','amount','transaction_date','description','document_url'].forEach((key) => setValue(key, item[key])); setValue('kitchen_id', item.kitchen_id); } modal.classList.remove('hidden'); };
  document.getElementById('finance-add').addEventListener('click', () => open()); document.getElementById('finance-close').addEventListener('click', () => modal.classList.add('hidden'));
  rows.addEventListener('click', async (event) => { const button = event.target.closest('button'); if (!button) return; try { if (button.dataset.edit) return open(button.dataset.edit); if (button.dataset.delete && confirm('Hapus transaksi ini?')) { await api('/api/admin/finance/transactions/'+button.dataset.delete, { method: 'DELETE' }); notify('Transaksi berhasil dihapus.'); load(); } } catch (error) { notify(error.message, true); } });
  form.addEventListener('submit', async (event) => { event.preventDefault(); const payload = Object.fromEntries(new FormData(form).entries()); payload.amount = Number(payload.amount); payload.kitchen_id = Number(payload.kitchen_id); try { const id = form.dataset.id; await api(id ? '/api/admin/finance/transactions/'+id : '/api/admin/finance/transactions', { method: id ? 'PATCH' : 'POST', headers: {'content-type':'application/json'}, body: JSON.stringify(payload) }); modal.classList.add('hidden'); notify(id ? 'Transaksi berhasil diperbarui.' : 'Transaksi berhasil dibuat.'); load(); } catch (error) { notify(error.message, true); } });
  loadOptions().then(load).catch((error) => notify(error.message, true));
})();
`;

export const KeuanganPage: FC = () => (
  <AdminLayout title="Kelola Keuangan" activePage="/admin/keuangan">
    <div><div class="flex flex-col sm:flex-row sm:items-center justify-between mb-8 gap-4"><div><h2 class="font-display-lg text-display-lg text-on-surface">Kelola Keuangan</h2><p class="font-body-md text-body-md text-on-surface-variant mt-1">Catat pemasukan, pengeluaran, dan bukti transaksi secara terpusat.</p></div><Button variant="primary" shape="pill" type="button" onclick="document.getElementById('finance-add').click()"><span class="material-symbols-outlined text-[18px]">add</span>Tambah Transaksi</Button></div>
      <div class="grid grid-cols-1 md:grid-cols-3 gap-4 mb-8"><div class="bg-surface-container-lowest rounded-xl p-card-padding shadow-sm"><p class="text-on-surface-variant">Saldo</p><h3 id="finance-balance" class="font-display-lg text-display-lg text-primary">-</h3></div><div class="bg-surface-container-lowest rounded-xl p-card-padding shadow-sm"><p class="text-on-surface-variant">Total Pemasukan</p><h3 id="finance-income" class="font-display-lg text-display-lg text-tertiary">-</h3></div><div class="bg-surface-container-lowest rounded-xl p-card-padding shadow-sm"><p class="text-on-surface-variant">Total Pengeluaran</p><h3 id="finance-expense" class="font-display-lg text-display-lg text-error">-</h3></div></div>
      <div id="finance-message" hidden></div><div class="bg-surface-container-lowest rounded-xl shadow-sm overflow-hidden"><div class="p-card-padding border-b border-surface-variant flex justify-between items-center"><h3 class="font-headline-md text-headline-md">Riwayat Transaksi</h3><a href="/admin/keuangan/statistik" class="text-primary">Lihat statistik</a></div><div class="overflow-x-auto"><table class="w-full text-left"><thead class="bg-surface-container-low"><tr><th class="p-3">Tanggal</th><th class="p-3">Transaksi</th><th class="p-3">Jenis/Kategori</th><th class="p-3 text-right">Nominal</th><th class="p-3 text-right">Aksi</th></tr></thead><tbody id="finance-rows"></tbody></table></div></div>
      <button id="finance-add" type="button" hidden>add</button><div id="finance-modal" class="hidden fixed inset-0 z-30 bg-black/30 p-4 overflow-y-auto"><div class="bg-surface-card max-w-2xl mx-auto mt-10 rounded-xl p-6"><div class="flex justify-between items-center mb-5"><h3 id="finance-modal-title" class="font-headline-md text-headline-md">Tambah Transaksi</h3><button id="finance-close" type="button" class="text-2xl" aria-label="Tutup">×</button></div><form id="finance-form" class="grid grid-cols-1 md:grid-cols-2 gap-4"><label>Jenis<select name="type" required class="mt-1 w-full border border-outline-variant rounded-lg p-2"><option value="IN">Pemasukan</option><option value="OUT">Pengeluaran</option></select></label><label>Dapur<select id="finance-kitchen" name="kitchen_id" required class="mt-1 w-full border border-outline-variant rounded-lg p-2"><option value="">Pilih dapur</option></select></label><label class="md:col-span-2">Judul<input name="title" required class="mt-1 w-full border border-outline-variant rounded-lg p-2" /></label><label>Kategori<input name="category" required class="mt-1 w-full border border-outline-variant rounded-lg p-2" /></label><label>Nominal<input name="amount" type="number" min="1" required class="mt-1 w-full border border-outline-variant rounded-lg p-2" /></label><label>Tanggal<input name="transaction_date" type="date" required class="mt-1 w-full border border-outline-variant rounded-lg p-2" /></label><label>Dokumen URL<input name="document_url" class="mt-1 w-full border border-outline-variant rounded-lg p-2" /></label><label class="md:col-span-2">Deskripsi<textarea name="description" class="mt-1 w-full border border-outline-variant rounded-lg p-2"></textarea></label><div class="md:col-span-2 flex justify-end gap-3"><button type="button" onclick="document.getElementById('finance-close').click()" class="border border-primary text-primary rounded-lg px-5 py-2">Batal</button><button type="submit" class="bg-primary text-on-primary rounded-lg px-5 py-2">Simpan Transaksi</button></div></form></div></div>
    </div><ClientScript>{script}</ClientScript>
  </AdminLayout>
);
