export const colors = {
  primary: '#4b329f',
  'on-primary': '#ffffff',
  'primary-container': '#634cb8',
  'on-primary-container': '#ddd3ff',
  'primary-fixed': '#e7deff',
  'primary-fixed-dim': '#cbbeff',
  'on-primary-fixed': '#1e0060',
  'on-primary-fixed-variant': '#4b329e',
  'inverse-primary': '#cbbeff',
  secondary: '#8a5100',
  'on-secondary': '#ffffff',
  'secondary-container': '#fd9d22',
  'on-secondary-container': '#673b00',
  'secondary-fixed': '#ffdcbd',
  'secondary-fixed-dim': '#ffb86e',
  'on-secondary-fixed': '#2c1600',
  'on-secondary-fixed-variant': '#693c00',
  tertiary: '#005320',
  'on-tertiary': '#ffffff',
  'tertiary-container': '#006e2d',
  'on-tertiary-container': '#7ff192',
  'tertiary-fixed': '#89fa9b',
  'tertiary-fixed-dim': '#6ddd81',
  'on-tertiary-fixed': '#002108',
  'on-tertiary-fixed-variant': '#005320',
  error: '#ba1a1a',
  'on-error': '#ffffff',
  'error-container': '#ffdad6',
  'on-error-container': '#93000a',
  background: '#f8f9fa',
  'on-background': '#191c1d',
  surface: '#f8f9fa',
  'surface-dim': '#d9dadb',
  'surface-bright': '#f8f9fa',
  'surface-container-lowest': '#ffffff',
  'surface-container-low': '#f3f4f5',
  'surface-container': '#edeeef',
  'surface-container-high': '#e7e8e9',
  'surface-container-highest': '#e1e3e4',
  'surface-variant': '#e1e3e4',
  'surface-tint': '#634cb8',
  'on-surface': '#191c1d',
  'on-surface-variant': '#484552',
  'inverse-surface': '#2e3132',
  'inverse-on-surface': '#f0f1f2',
  outline: '#797584',
  'outline-variant': '#cac4d4',
  'surface-card': '#ffffff',
  'border-subtle': '#e1e3e4',
  'on-surface-muted': '#484552',
} as const;

export const typography: Record<string, { fontSize: string; lineHeight: string; fontWeight: string; letterSpacing?: string }> = {
  'display-lg': { fontSize: '24px', lineHeight: '32px', fontWeight: '700' },
  'headline-md': { fontSize: '18px', lineHeight: '24px', fontWeight: '700' },
  'headline-sm': { fontSize: '16px', lineHeight: '22px', fontWeight: '600' },
  'headline-md-mobile': { fontSize: '16px', lineHeight: '22px', fontWeight: '700' },
  'body-lg': { fontSize: '16px', lineHeight: '24px', fontWeight: '400' },
  'body-md': { fontSize: '14px', lineHeight: '20px', fontWeight: '400' },
  'body-sm': { fontSize: '12px', lineHeight: '18px', fontWeight: '400' },
  'label-md': { fontSize: '12px', lineHeight: '16px', fontWeight: '600', letterSpacing: '0.02em' },
  'label-lg': { fontSize: '14px', lineHeight: '20px', fontWeight: '600' },
};

export const spacing = {
  'sidebar-width': '240px',
  'container-margin': '24px',
  'card-padding': '20px',
  gutter: '16px',
  'stack-md': '16px',
  'stack-sm': '8px',
  'container-max-width': '480px',
  'section-gap': '2rem',
  'form-stack': '1.25rem',
  'inline-padding': '1.5rem',
} as const;

export const borderRadius = {
  DEFAULT: '0.25rem',
  lg: '0.5rem',
  xl: '0.75rem',
  full: '9999px',
} as const;
